language: python

cache: pip

notifications:
  email: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

os:
  - linux
  - osx

git:
  depth: 3

before_install:
  - "sudo apt-get -qq update"
  - "sudo apt-get install -y graphviz"

install:
  - "pip install --upgrade pip wheel"
  - "pip install --only-binary=numpy,scipy numpy>1.10.0 scipy"
  - "pip install cython"
  - "pip install matplotlib"
  - "pip install nose2"
  - "pip install ddt"
  - "pip install git+git://github.com/Bernhard10/biopython.git@master#egg=biopython"
  - "pip install .[all]"
  - "mkdir mctools"
  - "wget http://major.iric.ca/MajorLabEn/MC-Tools_files/libmccore.dylib.1.6.2"
  - "mv libmccore.dylib.1.6.2 mctools/"
  - "wget http://major.iric.ca/MajorLabEn/MC-Tools_files/MC-Annotate.zip"
  - "unzip MC-Annotate.zip"
  - "mv MC-Annotate mctools/"
  - "export PATH=$PATH:$PWD/mctools/"
  - "mkdir ~/.config/forgi/"
  - "echo '{\"PDB_ANNOTATION_TOOL\": \"MC-Annotate\"}' >~/.config/forgi/config.json"


script:
  - "pip install ."
  - "nose2 test"
